#!/bin/sh

cd "$(dirname "$0")"

export LC_ALL=C

set -ex

# We need to remove the built files from the $(srcdir) in order to
# make the VPATH search work properly for the test builds.
make clean

while read id cc cflags
do
    abs_top_srcdir="$PWD"
    builddir="$PWD/_build-$id"
    prefix="$PWD/_prefix-$id"
    rm -rf "$builddir" "$prefix"
    (
	mkdir "$builddir"
	cd "$builddir"
	srcdir="${abs_top_srcdir}"
	cat>local.mk<<EOF
VPATH    = $srcdir
srcdir   = $srcdir
CC       = $cc
CFLAGS   = $cflags
CPPFLAGS = -I. -I$srcdir
prefix   = $prefix
EOF

	run_make() {
	    make -j -f "$srcdir/GNUmakefile" "$@"
	}

	run_make
	run_make check

	run_make install-nobuild
	(cd "$prefix" && find . -type f | sort) > after-installation.txt
	nl after-installation.txt
	if test -s after-installation.txt; then
	    :
	else
	    echo "Error: After installation, there should be files installed."
	    exit 1
	fi

	run_make uninstall
	(cd "$prefix" && find . -type f | sort) > after-uninstall.txt
	nl after-uninstall.txt
	if test -s after-uninstall.txt; then
	    echo "Error: After uninstall, there should be no files left."
	    exit 1
	fi
    )
done <<EOF
native-clang	clang	-Dbuilt_with="clang"
native-gcc	gcc	-Dbuilt_with="gcc"
EOF

# Note that at this time, the cflags part of the parameter list is
# only used as a placeholder.
