#!/bin/sh

cd "$(dirname "$0")"

export LC_ALL=C

set -ex

if test -f Makefile
then
    make distclean
fi

while read id cc cflags
do
    abs_top_srcdir="$PWD"
    builddir="$PWD/_build-$id"
    prefix="$PWD/_prefix-$id"
    rm -rf "$builddir" "$prefix"
    (
	mkdir "$builddir"
	cd "$builddir"
	../configure --prefix="$prefix" CC="$cc"

	run_make() {
	    make -j$(nproc) -l$(nproc) CFLAGS="$cflags" "$@"
	}

	run_make
	run_make check

	run_make install
	(cd "$prefix" && find . -type f | sort) > after-installation.txt
	nl after-installation.txt
	if test -s after-installation.txt; then
	    :
	else
	    echo "Error: After installation, there should be files installed."
	    exit 1
	fi

	run_make uninstall
	(cd "$prefix" && find . -type f | sort) > after-uninstall.txt
	nl after-uninstall.txt
	if test -s after-uninstall.txt; then
	    echo "Error: After uninstall, there should be no files left."
	    exit 1
	fi
    )
done <<EOF
native-clang	clang	-O2 -g -Wall -Wextra -Wmost -Werror -Wno-padded
native-gcc	gcc	-O2 -g -fanalyzer -fsanitize=undefined -Wall -Wextra -Werror
EOF
