#!/bin/sh
# debian/config file for beep
# copyright 2002-2009 by Gerfried Fuchs <rhonda@debian.at>
# Licenced under WTFPLv2

set -e

# Source debconf library.
. /usr/share/debconf/confmodule

# how to suid the beep program
db_input medium beep/suid_option || true
db_go

exit 0
