#!/bin/sh -e
# postrm for beep
# copyright 2002-2009 by Gerfried Fuchs <rhonda@debian.at>
# Licenced under BSD style

if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
