#!/bin/sh
# postrm for beep
# copyright 2002-2011 by Rhonda D'Vine <rhonda@debian.org>
# Licenced under WTFPLv2

set -e

if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi

#DEBHELPER#
