name: beep build CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: apt-get
      run: |
        sudo apt-get update
        sudo apt-get install -y automake autoconf
    - name: autoreconf
      run: autoreconf -vis
    - name: configure
      run: ./configure --prefix="${PWD}/_root"
    - name: make
      run: make
    - name: 'beep --help'
      run: |
        ./beep --help > beep-usage.from--help
        diff -u beep-usage.txt beep-usage.from--help
    - name: 'make check'
      run: make check
    - name: 'make install'
      run: make install
    - name: 'list installed files'
      run: (cd "$PWD/_root" && ls -l $(find . -type f | env LC_ALL=C sort) | nl)
    - name: 'make distcheck'
      run: make distcheck
